#!/bin/bash

set -e

echo "Le package est correctement desinstallé, pouvez-vous prendre un moment pour nous dire les raisons de cette desinstallation ? 
report at https://www.mathinfo-package.genielectrik.com/report"

exit 0
